import { DailyGuestInfo } from '../types';

export const HOME_DASHBOARD: DailyGuestInfo[] = [
  {
    date: '2020-09-25',
    arrivals: [
      {
        guestName: 'Richard Thompson',
        reservationId: 'b1',
        property: '1124 Chapman Avenue',
        channel: 'airbnb',
        checkIn: '2020-09-25T15:00',
        checkOut: '2020-10-05T11:00',
        parkingReserved: true,
        parkingSpot: 'Garage A - 12',
        specialRequests: ['Late check-in clearance', 'Grocery delivery on arrival'],
        flightNumber: 'UA 1245',
        transportation: 'Black car pickup 4:30 PM',
        notes: 'Guest requested local dining recommendations',
        eta: '16:45',
        delay: '15m',
        taskIds: ['task-b1-grocery-delivery', 'task-b1-late-checkin'],
      },
    ],
    departures: [
      {
        guestName: 'Evan Morris',
        reservationId: 'b19',
        property: 'Montrose Upstairs',
        channel: 'direct',
        checkIn: '2020-09-25T15:00',
        checkOut: '2020-10-03T11:00',
        parkingReserved: false,
        specialRequests: ['Late checkout waiver confirmed'],
        transportation: 'Uber scheduled for 9:30 AM',
        departureTime: '11:00',
        notes: 'Confirm late checkout waiver',
        taskIds: ['task-b19-waiver', 'task-b19-inspection'],
      },
    ],
    stays: [
      {
        guestName: 'Gina Howard',
        reservationId: 'b25',
        property: 'West End 105',
        channel: 'airbnb',
        checkIn: '2020-09-24T14:00',
        checkOut: '2020-10-02T11:00',
        parkingReserved: true,
        parkingSpot: 'Lot B - 5',
        specialRequests: ['Guest travelling with dog'],
        requests: ['Extra towels daily'],
        housekeeping: 'Change linens today',
        notes: 'Travels with small dog (approved)',
        taskIds: ['task-b25-pet-kit'],
      },
    ],
  },
  {
    date: '2020-09-26',
    arrivals: [
      {
        guestName: 'Haley Barnes',
        reservationId: 'b21',
        property: 'Teardrop Trailer',
        channel: 'airbnb',
        checkIn: '2020-09-26T14:00',
        checkOut: '2020-10-07T11:00',
        parkingReserved: true,
        parkingSpot: 'Lot C - 7',
        specialRequests: ['Vegan breakfast hamper'],
        transportation: 'Driving, ETA 5 PM',
        notes: 'Vegan breakfast items requested',
        taskIds: ['task-b21-vegan-hamper', 'task-b21-parking'],
      },
    ],
    departures: [],
    stays: [
      {
        guestName: 'Francisco Davis',
        reservationId: 'b8',
        property: '801 Campbell Unit A',
        channel: 'direct',
        checkIn: '2020-09-02T14:00',
        checkOut: '2020-09-04T11:00',
        parkingReserved: false,
        specialRequests: ['Coordinate ticket delivery'],
        requests: ['Fresh coffee beans delivery'],
        housekeeping: 'No service requested',
        notes: 'Deliver city tour tickets to room',
        taskIds: ['task-b8-tour-tickets', 'task-b8-fridge-sweep'],
      },
    ],
  },
  {
    date: '2020-09-27',
    arrivals: [
      {
        guestName: 'Jack Peterson',
        reservationId: 'b23',
        property: 'West End 102',
        channel: 'vrbo',
        checkIn: '2020-09-27T16:00',
        checkOut: '2020-10-06T10:00',
        parkingReserved: true,
        parkingSpot: 'Garage B - 18',
        specialRequests: ['Feather-free bedding'],
        flightNumber: 'DL 992',
        transportation: 'Airport shuttle drop-off 6 PM',
        notes: 'Allergic to feather pillows',
        taskIds: ['task-b23-plan', 'task-b23-towels', 'task-b23-shuttle'],
      },
    ],
    departures: [
      {
        guestName: 'Francisco Davis',
        reservationId: 'b8',
        property: '801 Campbell Unit A',
        channel: 'direct',
        checkIn: '2020-09-02T14:00',
        checkOut: '2020-09-04T11:00',
        parkingReserved: false,
        specialRequests: ['Pre-departure fridge sweep'],
        transportation: 'Rental car drop-off 11 AM',
        departureTime: '10:00',
        notes: 'Ensure fridge is emptied',
        taskIds: ['task-b8-tour-tickets', 'task-b8-fridge-sweep'],
      },
    ],
    stays: [
      {
        guestName: 'Christa Lee',
        reservationId: 'b5',
        property: '430 Church Bedford Hills',
        channel: 'vrbo',
        checkIn: '2020-09-02T16:00',
        checkOut: '2020-09-07T10:00',
        parkingReserved: true,
        parkingSpot: 'Lot A - 3',
        specialRequests: ['Portable crib setup'],
        requests: ['Add portable crib'],
        housekeeping: 'Mid-stay clean tomorrow',
        notes: 'Family of four, baby on site',
        taskIds: ['task-b5-crib', 'task-b5-midstay'],
      },
    ],
  },
];

export const getDashboard = (): DailyGuestInfo[] => HOME_DASHBOARD;
